### ISSUE TITLE
Cannot merge_obs if obsdata have scans.

### ISSUE THREAD

**Issue by danielpalumbo** [achael/eht-imaging#184] opened 2024-04-23 09:02 UTC
**Describe the bug**
The bug is caused by comparing an array to an empty list using ==.

**To Reproduce**
Here's a simple example using the public EHT data from 2017:
```
import ehtim as eh
obs = eh.obsdata.load_uvfits('/home/daniel/local_data/m87_data/zblcal+selfcal/hops_hi_3597_M87+zbl-dtcal_selfcal.uvfits')
obs2 = eh.obsdata.load_uvfits('/home/daniel/local_data/m87_data/zblcal+selfcal/hops_hi_3598_M87+zbl-dtcal_selfcal.uvfits')
eh.obsdata.merge_obs([obs,obs2])

```
**Expected behavior**
A new merged obsdata.

**Error**
in merge_obs(obs_List, force_merge)
   4731     mjd_offset = obs.mjd - mjd_ref
   4732     obs.data['time'] += mjd_offset * 24
-> 4733     if not(obs.scans is None or obs.scans == []):
   4734         obs.scans += mjd_offset * 24
   4736 # merge the data

ValueError: operands could not be broadcast together with shapes (18,2) (0,)

**Comment by achael** [comment] 2024-04-23 17:58
I wasn't seeing this  issue, but I think it is caused by a newer version of python than what I am running. I have replaced "obs.scans==[]" with "len(obs.scans)==0" and pushed the change to dev. Can you see if that fixes the issue?

**Comment by wumpus** [comment] 2024-05-10 17:29
is obs.scans a dataframe? if so you want `obs.scans.empty`

**Comment by achael** [comment] 2024-06-26 00:02
@danielpalumbo , the example you sent works for me now, can you verify if I can close this issue?

**Comment by danielpalumbo** [comment] 2024-06-26 00:11
Yes, I believe you can. Thanks!

**Closed** 2024-06-26 00:24 UTC
